/*
 * generated by Xtext 2.9.2
 */
package com.ifpen.manager.xtext.ide.contentassist.antlr;

import com.google.inject.Inject;
import com.ifpen.manager.xtext.ide.contentassist.antlr.internal.InternalProjectDslParser;
import com.ifpen.manager.xtext.services.ProjectDslGrammarAccess;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

public class ProjectDslParser extends AbstractContentAssistParser {

	@Inject
	private ProjectDslGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalProjectDslParser createParser() {
		InternalProjectDslParser result = new InternalProjectDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getTaskTypeAccess().getAlternatives(), "rule__TaskType__Alternatives");
					put(grammarAccess.getCompanyAccess().getGroup(), "rule__Company__Group__0");
					put(grammarAccess.getEmployeesAccess().getGroup(), "rule__Employees__Group__0");
					put(grammarAccess.getEmployeeAccess().getGroup(), "rule__Employee__Group__0");
					put(grammarAccess.getEmployeeAccess().getGroup_2(), "rule__Employee__Group_2__0");
					put(grammarAccess.getEmployeeAccess().getGroup_3(), "rule__Employee__Group_3__0");
					put(grammarAccess.getProjectAccess().getGroup(), "rule__Project__Group__0");
					put(grammarAccess.getCompanyAccess().getNameAssignment_1(), "rule__Company__NameAssignment_1");
					put(grammarAccess.getCompanyAccess().getEmployeesAssignment_2(), "rule__Company__EmployeesAssignment_2");
					put(grammarAccess.getCompanyAccess().getProjectAssignment_3(), "rule__Company__ProjectAssignment_3");
					put(grammarAccess.getEmployeesAccess().getEmployeesAssignment_2(), "rule__Employees__EmployeesAssignment_2");
					put(grammarAccess.getEmployeeAccess().getNameAssignment_1(), "rule__Employee__NameAssignment_1");
					put(grammarAccess.getEmployeeAccess().getWeightAssignment_2_1(), "rule__Employee__WeightAssignment_2_1");
					put(grammarAccess.getEmployeeAccess().getHeightAssignment_3_1(), "rule__Employee__HeightAssignment_3_1");
					put(grammarAccess.getProjectAccess().getNameAssignment_1(), "rule__Project__NameAssignment_1");
					put(grammarAccess.getProjectAccess().getTypeAssignment_3(), "rule__Project__TypeAssignment_3");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalProjectDslParser typedParser = (InternalProjectDslParser) parser;
			typedParser.entryRuleCompany();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public ProjectDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ProjectDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
