/*
 * generated by Xtext 2.9.2
 */
package com.ifpen.manager.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ProjectDslStandaloneSetup extends ProjectDslStandaloneSetupGenerated {

	def static void doSetup() {
		new ProjectDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
