/*
 * generated by Xtext 2.9.2
 */
package com.ifpen.manager.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ProjectDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/ifpen/manager/xtext/parser/antlr/internal/InternalProjectDsl.tokens");
	}
}
