/*
 * generated by Xtext 2.9.2
 */
package com.ifpen.manager.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractProjectDslScopeProvider extends DelegatingScopeProvider {
}
