/**
 * generated by Xtext 2.9.2
 */
package com.ifpen.manager.xtext.projectDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Company</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.ifpen.manager.xtext.projectDsl.Company#getName <em>Name</em>}</li>
 *   <li>{@link com.ifpen.manager.xtext.projectDsl.Company#getEmployees <em>Employees</em>}</li>
 *   <li>{@link com.ifpen.manager.xtext.projectDsl.Company#getProject <em>Project</em>}</li>
 * </ul>
 *
 * @see com.ifpen.manager.xtext.projectDsl.ProjectDslPackage#getCompany()
 * @model
 * @generated
 */
public interface Company extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.ifpen.manager.xtext.projectDsl.ProjectDslPackage#getCompany_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.ifpen.manager.xtext.projectDsl.Company#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Employees</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Employees</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Employees</em>' containment reference.
   * @see #setEmployees(Employees)
   * @see com.ifpen.manager.xtext.projectDsl.ProjectDslPackage#getCompany_Employees()
   * @model containment="true"
   * @generated
   */
  Employees getEmployees();

  /**
   * Sets the value of the '{@link com.ifpen.manager.xtext.projectDsl.Company#getEmployees <em>Employees</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Employees</em>' containment reference.
   * @see #getEmployees()
   * @generated
   */
  void setEmployees(Employees value);

  /**
   * Returns the value of the '<em><b>Project</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Project</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Project</em>' containment reference.
   * @see #setProject(Project)
   * @see com.ifpen.manager.xtext.projectDsl.ProjectDslPackage#getCompany_Project()
   * @model containment="true"
   * @generated
   */
  Project getProject();

  /**
   * Sets the value of the '{@link com.ifpen.manager.xtext.projectDsl.Company#getProject <em>Project</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Project</em>' containment reference.
   * @see #getProject()
   * @generated
   */
  void setProject(Project value);

} // Company
