/**
 * generated by Xtext 2.9.2
 */
package com.ifpen.manager.xtext.projectDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.ifpen.manager.xtext.projectDsl.ProjectDslFactory
 * @model kind="package"
 * @generated
 */
public interface ProjectDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "projectDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ifpen.com/manager/xtext/ProjectDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "projectDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ProjectDslPackage eINSTANCE = com.ifpen.manager.xtext.projectDsl.impl.ProjectDslPackageImpl.init();

  /**
   * The meta object id for the '{@link com.ifpen.manager.xtext.projectDsl.impl.CompanyImpl <em>Company</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ifpen.manager.xtext.projectDsl.impl.CompanyImpl
   * @see com.ifpen.manager.xtext.projectDsl.impl.ProjectDslPackageImpl#getCompany()
   * @generated
   */
  int COMPANY = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPANY__NAME = 0;

  /**
   * The feature id for the '<em><b>Employees</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPANY__EMPLOYEES = 1;

  /**
   * The feature id for the '<em><b>Project</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPANY__PROJECT = 2;

  /**
   * The number of structural features of the '<em>Company</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPANY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link com.ifpen.manager.xtext.projectDsl.impl.EmployeesImpl <em>Employees</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ifpen.manager.xtext.projectDsl.impl.EmployeesImpl
   * @see com.ifpen.manager.xtext.projectDsl.impl.ProjectDslPackageImpl#getEmployees()
   * @generated
   */
  int EMPLOYEES = 1;

  /**
   * The feature id for the '<em><b>Employees</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMPLOYEES__EMPLOYEES = 0;

  /**
   * The number of structural features of the '<em>Employees</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMPLOYEES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.ifpen.manager.xtext.projectDsl.impl.EmployeeImpl <em>Employee</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ifpen.manager.xtext.projectDsl.impl.EmployeeImpl
   * @see com.ifpen.manager.xtext.projectDsl.impl.ProjectDslPackageImpl#getEmployee()
   * @generated
   */
  int EMPLOYEE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMPLOYEE__NAME = 0;

  /**
   * The feature id for the '<em><b>Weight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMPLOYEE__WEIGHT = 1;

  /**
   * The feature id for the '<em><b>Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMPLOYEE__HEIGHT = 2;

  /**
   * The number of structural features of the '<em>Employee</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMPLOYEE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link com.ifpen.manager.xtext.projectDsl.impl.ProjectImpl <em>Project</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ifpen.manager.xtext.projectDsl.impl.ProjectImpl
   * @see com.ifpen.manager.xtext.projectDsl.impl.ProjectDslPackageImpl#getProject()
   * @generated
   */
  int PROJECT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT__TYPE = 1;

  /**
   * The feature id for the '<em><b>Tasks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT__TASKS = 2;

  /**
   * The number of structural features of the '<em>Project</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link com.ifpen.manager.xtext.projectDsl.impl.TaskImpl <em>Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ifpen.manager.xtext.projectDsl.impl.TaskImpl
   * @see com.ifpen.manager.xtext.projectDsl.impl.ProjectDslPackageImpl#getTask()
   * @generated
   */
  int TASK = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__TYPE = 1;

  /**
   * The number of structural features of the '<em>Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.ifpen.manager.xtext.projectDsl.taskType <em>task Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ifpen.manager.xtext.projectDsl.taskType
   * @see com.ifpen.manager.xtext.projectDsl.impl.ProjectDslPackageImpl#gettaskType()
   * @generated
   */
  int TASK_TYPE = 5;


  /**
   * Returns the meta object for class '{@link com.ifpen.manager.xtext.projectDsl.Company <em>Company</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Company</em>'.
   * @see com.ifpen.manager.xtext.projectDsl.Company
   * @generated
   */
  EClass getCompany();

  /**
   * Returns the meta object for the attribute '{@link com.ifpen.manager.xtext.projectDsl.Company#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.ifpen.manager.xtext.projectDsl.Company#getName()
   * @see #getCompany()
   * @generated
   */
  EAttribute getCompany_Name();

  /**
   * Returns the meta object for the containment reference '{@link com.ifpen.manager.xtext.projectDsl.Company#getEmployees <em>Employees</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Employees</em>'.
   * @see com.ifpen.manager.xtext.projectDsl.Company#getEmployees()
   * @see #getCompany()
   * @generated
   */
  EReference getCompany_Employees();

  /**
   * Returns the meta object for the containment reference '{@link com.ifpen.manager.xtext.projectDsl.Company#getProject <em>Project</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Project</em>'.
   * @see com.ifpen.manager.xtext.projectDsl.Company#getProject()
   * @see #getCompany()
   * @generated
   */
  EReference getCompany_Project();

  /**
   * Returns the meta object for class '{@link com.ifpen.manager.xtext.projectDsl.Employees <em>Employees</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Employees</em>'.
   * @see com.ifpen.manager.xtext.projectDsl.Employees
   * @generated
   */
  EClass getEmployees();

  /**
   * Returns the meta object for the containment reference list '{@link com.ifpen.manager.xtext.projectDsl.Employees#getEmployees <em>Employees</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Employees</em>'.
   * @see com.ifpen.manager.xtext.projectDsl.Employees#getEmployees()
   * @see #getEmployees()
   * @generated
   */
  EReference getEmployees_Employees();

  /**
   * Returns the meta object for class '{@link com.ifpen.manager.xtext.projectDsl.Employee <em>Employee</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Employee</em>'.
   * @see com.ifpen.manager.xtext.projectDsl.Employee
   * @generated
   */
  EClass getEmployee();

  /**
   * Returns the meta object for the attribute '{@link com.ifpen.manager.xtext.projectDsl.Employee#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.ifpen.manager.xtext.projectDsl.Employee#getName()
   * @see #getEmployee()
   * @generated
   */
  EAttribute getEmployee_Name();

  /**
   * Returns the meta object for the attribute '{@link com.ifpen.manager.xtext.projectDsl.Employee#getWeight <em>Weight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Weight</em>'.
   * @see com.ifpen.manager.xtext.projectDsl.Employee#getWeight()
   * @see #getEmployee()
   * @generated
   */
  EAttribute getEmployee_Weight();

  /**
   * Returns the meta object for the attribute '{@link com.ifpen.manager.xtext.projectDsl.Employee#getHeight <em>Height</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Height</em>'.
   * @see com.ifpen.manager.xtext.projectDsl.Employee#getHeight()
   * @see #getEmployee()
   * @generated
   */
  EAttribute getEmployee_Height();

  /**
   * Returns the meta object for class '{@link com.ifpen.manager.xtext.projectDsl.Project <em>Project</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Project</em>'.
   * @see com.ifpen.manager.xtext.projectDsl.Project
   * @generated
   */
  EClass getProject();

  /**
   * Returns the meta object for the attribute '{@link com.ifpen.manager.xtext.projectDsl.Project#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.ifpen.manager.xtext.projectDsl.Project#getName()
   * @see #getProject()
   * @generated
   */
  EAttribute getProject_Name();

  /**
   * Returns the meta object for the attribute '{@link com.ifpen.manager.xtext.projectDsl.Project#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see com.ifpen.manager.xtext.projectDsl.Project#getType()
   * @see #getProject()
   * @generated
   */
  EAttribute getProject_Type();

  /**
   * Returns the meta object for the containment reference list '{@link com.ifpen.manager.xtext.projectDsl.Project#getTasks <em>Tasks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tasks</em>'.
   * @see com.ifpen.manager.xtext.projectDsl.Project#getTasks()
   * @see #getProject()
   * @generated
   */
  EReference getProject_Tasks();

  /**
   * Returns the meta object for class '{@link com.ifpen.manager.xtext.projectDsl.Task <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task</em>'.
   * @see com.ifpen.manager.xtext.projectDsl.Task
   * @generated
   */
  EClass getTask();

  /**
   * Returns the meta object for the attribute '{@link com.ifpen.manager.xtext.projectDsl.Task#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.ifpen.manager.xtext.projectDsl.Task#getName()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Name();

  /**
   * Returns the meta object for the attribute '{@link com.ifpen.manager.xtext.projectDsl.Task#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see com.ifpen.manager.xtext.projectDsl.Task#getType()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Type();

  /**
   * Returns the meta object for enum '{@link com.ifpen.manager.xtext.projectDsl.taskType <em>task Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>task Type</em>'.
   * @see com.ifpen.manager.xtext.projectDsl.taskType
   * @generated
   */
  EEnum gettaskType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ProjectDslFactory getProjectDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.ifpen.manager.xtext.projectDsl.impl.CompanyImpl <em>Company</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ifpen.manager.xtext.projectDsl.impl.CompanyImpl
     * @see com.ifpen.manager.xtext.projectDsl.impl.ProjectDslPackageImpl#getCompany()
     * @generated
     */
    EClass COMPANY = eINSTANCE.getCompany();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPANY__NAME = eINSTANCE.getCompany_Name();

    /**
     * The meta object literal for the '<em><b>Employees</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPANY__EMPLOYEES = eINSTANCE.getCompany_Employees();

    /**
     * The meta object literal for the '<em><b>Project</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPANY__PROJECT = eINSTANCE.getCompany_Project();

    /**
     * The meta object literal for the '{@link com.ifpen.manager.xtext.projectDsl.impl.EmployeesImpl <em>Employees</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ifpen.manager.xtext.projectDsl.impl.EmployeesImpl
     * @see com.ifpen.manager.xtext.projectDsl.impl.ProjectDslPackageImpl#getEmployees()
     * @generated
     */
    EClass EMPLOYEES = eINSTANCE.getEmployees();

    /**
     * The meta object literal for the '<em><b>Employees</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EMPLOYEES__EMPLOYEES = eINSTANCE.getEmployees_Employees();

    /**
     * The meta object literal for the '{@link com.ifpen.manager.xtext.projectDsl.impl.EmployeeImpl <em>Employee</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ifpen.manager.xtext.projectDsl.impl.EmployeeImpl
     * @see com.ifpen.manager.xtext.projectDsl.impl.ProjectDslPackageImpl#getEmployee()
     * @generated
     */
    EClass EMPLOYEE = eINSTANCE.getEmployee();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EMPLOYEE__NAME = eINSTANCE.getEmployee_Name();

    /**
     * The meta object literal for the '<em><b>Weight</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EMPLOYEE__WEIGHT = eINSTANCE.getEmployee_Weight();

    /**
     * The meta object literal for the '<em><b>Height</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EMPLOYEE__HEIGHT = eINSTANCE.getEmployee_Height();

    /**
     * The meta object literal for the '{@link com.ifpen.manager.xtext.projectDsl.impl.ProjectImpl <em>Project</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ifpen.manager.xtext.projectDsl.impl.ProjectImpl
     * @see com.ifpen.manager.xtext.projectDsl.impl.ProjectDslPackageImpl#getProject()
     * @generated
     */
    EClass PROJECT = eINSTANCE.getProject();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROJECT__NAME = eINSTANCE.getProject_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROJECT__TYPE = eINSTANCE.getProject_Type();

    /**
     * The meta object literal for the '<em><b>Tasks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROJECT__TASKS = eINSTANCE.getProject_Tasks();

    /**
     * The meta object literal for the '{@link com.ifpen.manager.xtext.projectDsl.impl.TaskImpl <em>Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ifpen.manager.xtext.projectDsl.impl.TaskImpl
     * @see com.ifpen.manager.xtext.projectDsl.impl.ProjectDslPackageImpl#getTask()
     * @generated
     */
    EClass TASK = eINSTANCE.getTask();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__NAME = eINSTANCE.getTask_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__TYPE = eINSTANCE.getTask_Type();

    /**
     * The meta object literal for the '{@link com.ifpen.manager.xtext.projectDsl.taskType <em>task Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ifpen.manager.xtext.projectDsl.taskType
     * @see com.ifpen.manager.xtext.projectDsl.impl.ProjectDslPackageImpl#gettaskType()
     * @generated
     */
    EEnum TASK_TYPE = eINSTANCE.gettaskType();

  }

} //ProjectDslPackage
