/*
 * generated by Xtext 2.9.2
 */
package com.ifpen.manager.xtext.validation

import com.ifpen.manager.xtext.projectDsl.Employee
import com.ifpen.manager.xtext.projectDsl.ProjectDslPackage
import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class ProjectDslValidator extends AbstractProjectDslValidator {

//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					ProjectDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}


	public static val INVALID_WEIGHT = "invalidWeight"

	@Check
	def checkWeight(Employee e) {

		if (e.weight > 0 && e.weight < 30) {
			warning('Employee trop leger', ProjectDslPackage.Literals.EMPLOYEE__WEIGHT, INVALID_WEIGHT)
		}
	}

}
